name: hillapp
version: 1.0.0+1
description: HillApp - Health Tracker

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  fl_chart: ^0.70.0
  crypto: ^3.0.3
  table_calendar: ^3.0.8
  sqflite: ^2.0.0+4
  intl: ^0.19.0
  path: ^1.8.0
  uuid: ^3.0.0
  logger: ^1.1.0
  flutter_spinkit: ^5.1.0
  google_fonts: ^4.0.4
  flutter_svg: ^1.1.6
  flutter_local_notifications: ^14.1.5
  timezone: ^0.9.0
  flutter_secure_storage: ^8.0.0
  image_picker: ^0.8.5+3          # Добавлено для выбора аватарки
  url_launcher: ^6.1.7           # Добавлено для открытия внешних ссылок
  flutter_localizations:         # Добавлено для поддержки нескольких языков
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  assets:
    - assets/images/
    - assets/data/medications.json
    - assets/icons/register.svg
    - assets/icons/app_icon.png
    - lib/analysis/data/analysis_data.json
  uses-material-design: true
